### ISSUE TITLE
Character Placement While Fishing

### ISSUE THREAD

**Issue by machetemike** [miracle091/Better-Fisher#15]
When the bot arrives at the designated fishing position it always passes the point and then turns around to run back to it finally stopping. 

This causes your character to look away from the water and cast on the dirt. 

On your screen it will appear as you are facing the water but on others you are not. 

Makes it pretty easy to spot an AFK fisher.

**Comment by miracle091** [comment]
Is already implemented the facing at water, you just need to set better the fishing spot.

**Comment by machetemike** [comment]
What do you mean by set better? Using 0.9c - fresh install except for fishing spot. my fishing spot is close to the default one and it's still doing it. Turns around faces the cliff instead of the water then just before it casts, it faces the water. However on other clients screens I'm still facing the cliff.

**Comment by miracle091** [comment]
Set fishing spot again but this time look at water before set it.

StartFishing.lua - line 172: `selfPlayer:SetRotation(ProfileEditor.CurrentProfile:GetFishSpotRotation())`

**Comment by machetemike** [comment]
I reset it and it's still turning around after arriving at the spot then facing the water a nanosecond just before casting.

**Comment by machetemike** [comment]
So I do see that it now faces the water BUT what happens is, it faces away from the water, casts, cancels cast, faces water, casts again. Kind of obvious still.

**Comment by miracle091** [comment]
The only thing i can do, until navigation become a little better...is turning just 180° when come back to spot.

**Comment by miracle091** [comment]
Check the new versions.

**Comment by miracle091** [comment]
Fixed
