### ISSUE TITLE
Unable to repair / force repair

### ISSUE THREAD

**Issue by Nyett** [miracle091/Better-Fisher#19]
Using the latest (development) build

I am trying to bot Thermian Cliff and the bot simply will not repair no matter what I do.
The repair NPC is set correctly (Curtis @ Olvia)

Everything except for repair is working, I have not tried another spot.

**Comment by Ipodbob** [comment]
I have this issue too, won't repair at Olivia

**Comment by miracle091** [comment]
I need more informations...

**Comment by Nyett** [comment]
When the bot has finished fishing, it will not go to the repair npc and repair broken rods. 
I have tried pressing 'Force Repair' however that doesn't do anything and nothing shows up in the console when I press the button either.

I can not even clear the Repair NPC nor can I set the repair npc, I do not know why.

**Comment by miracle091** [comment]
Fixed
