### ISSUE TITLE
Does not jump properly when swimming

### ISSUE THREAD

**Issue by Ipodbob** [miracle091/Better-Fisher#23]
The latest developer "Beta C" version jumps to early whilst going from the swimming position made with a connect and never makes it onto the boat, thus getting stuck underneath it.

I am using a fishing costume, but also happens when no costume is present, tested with and without a _things_ and it happens every time. Currently on movement speed 4.

Everything else seems to function correctly other than climbing on the boat. Hope this info helps.  The normal fisher manages to climb onto the boat but it just swims and then climbs up rather than jumping on.

**Comment by miracle091** [comment]
Today i check it.
