### ISSUE TITLE
Dialog not opened loop.

### ISSUE THREAD

**Issue by crackedghouL** [miracle091/Better-Fisher#33]
Submitting the same issue as in official repo with adjusted lines
This loop happens when the Dialog didn't open in self.state == 2 
`	if self.state == 2 then -- 2 = create sell list
		if not Dialog.IsTalking then
			print(self.Settings.NpcName .. " dialog didn't open")
			self:Exit()
			return
		end`

self:Exit() sets the state to 0 -> TradeManagerState:Run() doesn't advance further if `vendorPosition.Distance3DFromMe > 300` doesn't return true. 
this results in an endless loop because NPCs don't become interactable before `vendorPosition.Distance3DFromMe = 220`, at least for my witch that is.

next thing that happens is self:Exit() at line 281 repeating the above.
possible fixes: 
- if Dialog doesn't open in self.State == 3 set state = 1 before self:Exit
- implement else condition for `if TradeManagerPosition.Distance3DFromMe > 300` where state again gets set to 1 
`else
if not Dialog.IsTalking then
Navigator.MoveTo(vendorPosition, nil, Bot.Settings.PlayerRun)
self.state = 1
end`
- reduce Distance check from 300 to 200

note: this loop only occurs on full inventory(needtorun returned true)

**Comment by crackedghouL** [comment]
second and third fix seem to work well for me, 1st one is bogus just results in a different loop.

**Comment by miracle091** [comment]
0.9e BETA have just third fix, should work for most of the people.
Btw i leave this open until i found a better a way to fix this.
